// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.6.1
// source: users/v1/users.proto

package users_v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	User_UserLoginV1_FullMethodName    = "/users.v1.User/UserLoginV1"
	User_UserRegisterV1_FullMethodName = "/users.v1.User/UserRegisterV1"
	User_GetUserV1_FullMethodName      = "/users.v1.User/GetUserV1"
	User_UpdateUserV1_FullMethodName   = "/users.v1.User/UpdateUserV1"
)

// UserClient is the client API for User service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserClient interface {
	UserLoginV1(ctx context.Context, in *UserLoginV1Request, opts ...grpc.CallOption) (*UserLoginV1Response, error)
	UserRegisterV1(ctx context.Context, in *UserRegisterV1Request, opts ...grpc.CallOption) (*UserRegisterV1Response, error)
	GetUserV1(ctx context.Context, in *GetUserV1Request, opts ...grpc.CallOption) (*GetUserV1Response, error)
	UpdateUserV1(ctx context.Context, in *UpdateUserV1Request, opts ...grpc.CallOption) (*UpdateUserV1Response, error)
}

type userClient struct {
	cc grpc.ClientConnInterface
}

func NewUserClient(cc grpc.ClientConnInterface) UserClient {
	return &userClient{cc}
}

func (c *userClient) UserLoginV1(ctx context.Context, in *UserLoginV1Request, opts ...grpc.CallOption) (*UserLoginV1Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserLoginV1Response)
	err := c.cc.Invoke(ctx, User_UserLoginV1_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) UserRegisterV1(ctx context.Context, in *UserRegisterV1Request, opts ...grpc.CallOption) (*UserRegisterV1Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserRegisterV1Response)
	err := c.cc.Invoke(ctx, User_UserRegisterV1_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) GetUserV1(ctx context.Context, in *GetUserV1Request, opts ...grpc.CallOption) (*GetUserV1Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserV1Response)
	err := c.cc.Invoke(ctx, User_GetUserV1_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) UpdateUserV1(ctx context.Context, in *UpdateUserV1Request, opts ...grpc.CallOption) (*UpdateUserV1Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateUserV1Response)
	err := c.cc.Invoke(ctx, User_UpdateUserV1_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServer is the server API for User service.
// All implementations must embed UnimplementedUserServer
// for forward compatibility.
type UserServer interface {
	UserLoginV1(context.Context, *UserLoginV1Request) (*UserLoginV1Response, error)
	UserRegisterV1(context.Context, *UserRegisterV1Request) (*UserRegisterV1Response, error)
	GetUserV1(context.Context, *GetUserV1Request) (*GetUserV1Response, error)
	UpdateUserV1(context.Context, *UpdateUserV1Request) (*UpdateUserV1Response, error)
	mustEmbedUnimplementedUserServer()
}

// UnimplementedUserServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserServer struct{}

func (UnimplementedUserServer) UserLoginV1(context.Context, *UserLoginV1Request) (*UserLoginV1Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserLoginV1 not implemented")
}
func (UnimplementedUserServer) UserRegisterV1(context.Context, *UserRegisterV1Request) (*UserRegisterV1Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserRegisterV1 not implemented")
}
func (UnimplementedUserServer) GetUserV1(context.Context, *GetUserV1Request) (*GetUserV1Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserV1 not implemented")
}
func (UnimplementedUserServer) UpdateUserV1(context.Context, *UpdateUserV1Request) (*UpdateUserV1Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUserV1 not implemented")
}
func (UnimplementedUserServer) mustEmbedUnimplementedUserServer() {}
func (UnimplementedUserServer) testEmbeddedByValue()              {}

// UnsafeUserServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserServer will
// result in compilation errors.
type UnsafeUserServer interface {
	mustEmbedUnimplementedUserServer()
}

func RegisterUserServer(s grpc.ServiceRegistrar, srv UserServer) {
	// If the following call pancis, it indicates UnimplementedUserServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&User_ServiceDesc, srv)
}

func _User_UserLoginV1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserLoginV1Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).UserLoginV1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_UserLoginV1_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).UserLoginV1(ctx, req.(*UserLoginV1Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_UserRegisterV1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRegisterV1Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).UserRegisterV1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_UserRegisterV1_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).UserRegisterV1(ctx, req.(*UserRegisterV1Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_GetUserV1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserV1Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).GetUserV1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_GetUserV1_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).GetUserV1(ctx, req.(*GetUserV1Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_UpdateUserV1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserV1Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).UpdateUserV1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_UpdateUserV1_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).UpdateUserV1(ctx, req.(*UpdateUserV1Request))
	}
	return interceptor(ctx, in, info, handler)
}

// User_ServiceDesc is the grpc.ServiceDesc for User service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var User_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "users.v1.User",
	HandlerType: (*UserServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UserLoginV1",
			Handler:    _User_UserLoginV1_Handler,
		},
		{
			MethodName: "UserRegisterV1",
			Handler:    _User_UserRegisterV1_Handler,
		},
		{
			MethodName: "GetUserV1",
			Handler:    _User_GetUserV1_Handler,
		},
		{
			MethodName: "UpdateUserV1",
			Handler:    _User_UpdateUserV1_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "users/v1/users.proto",
}
